#version 120
// Generated by tools/generate.py.
#define BLOHO_DIMENSION 0
#define BLOHO_TEXTURED
#define BLOHO_LIGHTMAP
#define BLOHO_SURFACE
#define BLOHO_FAMILY 4.0
#include "/program/gbuffer/geometry.vsh"
