#!/usr/bin/env python3
"""Generate thin engine entry points; implementation lives in shaders/program.

Run with --check in CI to catch missing/stale wrappers or render-state settings.
No third-party shader source is an input to this generator.
"""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
SHADERS = ROOT / 'shaders'
# Flags express engine input availability and metadata ownership.
PROGRAMS = {
    'basic': (),
    'line': (),
    'textured': ('TEXTURED',),
    'textured_lit': ('TEXTURED', 'LIGHTMAP'),
    'skybasic': (),
    'skytextured': ('TEXTURED',),
    'clouds': ('VANILLA_CLOUDS',),
    'terrain': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'TERRAIN', 'FAMILY 1.0'),
    'block': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'BLOCK_ENTITY', 'ENTITY_TINT', 'FAMILY 2.0'),
    'entities': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'ENTITY', 'ENTITY_TINT', 'FAMILY 3.0'),
    'entities_glowing': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'ENTITY', 'ENTITY_TINT', 'FAMILY 3.0'),
    'hand': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'FAMILY 4.0'),
    'water': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'TERRAIN', 'FAMILY 5.0'),
    'hand_water': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'FAMILY 6.0'),
    'weather': ('TEXTURED', 'LIGHTMAP'),
    'damagedblock': ('TEXTURED',),
    'armor_glint': ('TEXTURED',),
    'spidereyes': ('TEXTURED',),
    'beaconbeam': ('TEXTURED',),
}
WORLDS = {'': 0, 'world0': 0, 'world-1': -1, 'world1': 1}
FOGGED = {'basic', 'line', 'textured', 'textured_lit', 'clouds', 'terrain',
          'block', 'entities', 'entities_glowing', 'water', 'weather',
          'armor_glint', 'spidereyes', 'beaconbeam'}
SCREEN_PROGRAMS = [
    ('deferred', 'deferred/baseline.fsh', '0', ''),
    ('composite', 'composite/baseline.fsh', '0', ''),
    ('composite1', 'composite/bloom_extract.fsh', '4', ''),
    ('composite2', 'composite/bloom_blur.fsh', '5', 'BLOHO_BLUR_HORIZONTAL'),
    ('composite3', 'composite/bloom_blur.fsh', '4', ''),
    ('final', 'final.fsh', '', ''),
]


def generated_files():
    for world, dimension in WORLDS.items():
        for name, flags in PROGRAMS.items():
            if name in FOGGED:
                flags = flags + ('FOGGED',)
            if name in ('armor_glint', 'spidereyes'):
                flags = flags + ('ADDITIVE',)
            for ext in ('vsh', 'fsh'):
                text = '#version 120\n// Generated by tools/generate.py.\n'
                text += f'#define BLOHO_DIMENSION {dimension}\n'
                text += ''.join(f'#define BLOHO_{flag}\n' for flag in flags)
                if ext == 'fsh':
                    text += '/* DRAWBUFFERS:' + ('0123' if 'SURFACE' in flags else '0') + ' */\n'
                text += f'#include "/program/gbuffer/geometry.{ext}"\n'
                yield SHADERS / world / f'gbuffers_{name}.{ext}', text
        for name, fragment, outputs, define in SCREEN_PROGRAMS:
            for ext in ('vsh', 'fsh'):
                text = '#version 120\n// Generated by tools/generate.py.\n'
                text += f'#define BLOHO_DIMENSION {dimension}\n'
                if define:
                    text += f'#define {define}\n'
                if ext == 'fsh' and name != 'final':
                    text += f'/* DRAWBUFFERS:{outputs} */\n'
                target = 'fullscreen.vsh' if ext == 'vsh' else fragment
                text += f'#include "/program/{target}"\n'
                yield SHADERS / world / f'{name}.{ext}', text

    properties = '''# BlohoShaders atmosphere milestone. Generated by tools/generate.py.
# Preserve vanilla directional shading and AO in vertex RGB, leaving alpha intact.
oldLighting=true
separateAo=false
screen=<profile> [BLOOM] [FOG] [CLOUDS]
screen.BLOOM=BLOHO_BLOOM BLOOM_STRENGTH BLOOM_THRESHOLD BLOOM_RADIUS
screen.FOG=BLOHO_FOG FOG_STRENGTH
screen.CLOUDS=BLOHO_CLOUDS CLOUD_COVERAGE CLOUD_HEIGHT CLOUD_SPEED
sliders=BLOOM_STRENGTH BLOOM_THRESHOLD BLOOM_RADIUS FOG_STRENGTH CLOUD_COVERAGE CLOUD_HEIGHT CLOUD_SPEED
profile.BASELINE=BLOHO_BLOOM=0 BLOHO_FOG=0 BLOHO_CLOUDS=0
profile.BALANCED=BLOHO_BLOOM=1 BLOHO_FOG=1 BLOHO_CLOUDS=1 BLOOM_STRENGTH=0.22 BLOOM_THRESHOLD=0.75 BLOOM_RADIUS=2.0 FOG_STRENGTH=0.7 CLOUD_COVERAGE=0.52 CLOUD_HEIGHT=224.0 CLOUD_SPEED=1.0
size.buffer.colortex4=0.5 0.5
size.buffer.colortex5=0.5 0.5
# Keep engine defaults for sky, clouds, sun, moon, depth, alpha test, and scene blending.
# Disable blending only for metadata. Per-draw scene blending remains engine-owned.
'''
    for world in WORLDS:
        for name, flags in PROGRAMS.items():
            if 'SURFACE' in flags:
                program = (world + '/' if world else '') + 'gbuffers_' + name
                for target in (1, 2, 3):
                    properties += f'blend.{program}.colortex{target}=off\n'
    yield SHADERS / 'shaders.properties', properties


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, text in generated_files():
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if stale:
        raise SystemExit('Stale generated files:\n' + '\n'.join(stale))
    print('Entry points and render state: ' + ('verified' if args.check else 'generated'))


if __name__ == '__main__':
    main()
