#!/usr/bin/env python3
"""Generate thin engine entry points; implementation lives in shaders/program.

Run with --check in CI to catch missing/stale wrappers or render-state settings.
No third-party shader source is an input to this generator.
"""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
SHADERS = ROOT / 'shaders'
# Flags express engine input availability and metadata ownership.
PROGRAMS = {
    'basic': (),
    'line': (),
    'textured': ('TEXTURED',),
    'textured_lit': ('TEXTURED', 'LIGHTMAP'),
    'skybasic': (),
    'skytextured': ('TEXTURED',),
    'clouds': (),
    'terrain': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'TERRAIN', 'FAMILY 1.0'),
    'block': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'BLOCK_ENTITY', 'ENTITY_TINT', 'FAMILY 2.0'),
    'entities': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'ENTITY', 'ENTITY_TINT', 'FAMILY 3.0'),
    'entities_glowing': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'ENTITY', 'ENTITY_TINT', 'FAMILY 3.0'),
    'hand': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'FAMILY 4.0'),
    'water': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'TERRAIN', 'FAMILY 5.0'),
    'hand_water': ('TEXTURED', 'LIGHTMAP', 'SURFACE', 'FAMILY 6.0'),
    'weather': ('TEXTURED', 'LIGHTMAP'),
    'damagedblock': ('TEXTURED',),
    'armor_glint': ('TEXTURED',),
    'spidereyes': ('TEXTURED',),
    'beaconbeam': ('TEXTURED',),
}
WORLDS = {'': 0, 'world0': 0, 'world-1': -1, 'world1': 1}


def generated_files():
    for world, dimension in WORLDS.items():
        for name, flags in PROGRAMS.items():
            for ext in ('vsh', 'fsh'):
                text = '#version 120\n// Generated by tools/generate.py.\n'
                text += f'#define BLOHO_DIMENSION {dimension}\n'
                text += ''.join(f'#define BLOHO_{flag}\n' for flag in flags)
                if ext == 'fsh':
                    text += '/* DRAWBUFFERS:' + ('0123' if 'SURFACE' in flags else '0') + ' */\n'
                text += f'#include "/program/gbuffer/geometry.{ext}"\n'
                yield SHADERS / world / f'gbuffers_{name}.{ext}', text
        for name, fragment in [('deferred', 'deferred/baseline.fsh'),
                               ('composite', 'composite/baseline.fsh'), ('final', 'final.fsh')]:
            for ext in ('vsh', 'fsh'):
                text = '#version 120\n// Generated by tools/generate.py.\n'
                text += f'#define BLOHO_DIMENSION {dimension}\n'
                if ext == 'fsh' and name != 'final':
                    text += '/* DRAWBUFFERS:0 */\n'
                target = 'fullscreen.vsh' if ext == 'vsh' else fragment
                text += f'#include "/program/{target}"\n'
                yield SHADERS / world / f'{name}.{ext}', text

    properties = '''# BlohoShaders baseline. Generated by tools/generate.py.
# Preserve vanilla directional shading and AO in vertex RGB, leaving alpha intact.
oldLighting=true
separateAo=false
# Keep engine defaults for sky, clouds, sun, moon, depth, alpha test, and scene blending.
# Disable blending only for metadata. Per-draw scene blending remains engine-owned.
'''
    for world in WORLDS:
        for name, flags in PROGRAMS.items():
            if 'SURFACE' in flags:
                program = (world + '/' if world else '') + 'gbuffers_' + name
                for target in (1, 2, 3):
                    properties += f'blend.{program}.colortex{target}=off\n'
    yield SHADERS / 'shaders.properties', properties


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, text in generated_files():
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if stale:
        raise SystemExit('Stale generated files:\n' + '\n'.join(stale))
    print('Entry points and render state: ' + ('verified' if args.check else 'generated'))


if __name__ == '__main__':
    main()
